# configuration.yaml
application_port:
  port: 8000
  host: "127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "tawansongsang.k@gmail.com"
